version: "3"
services:
    app:
        container_name: fapi02_vd
        build:
            dockerfile: Dockerfile
            context: .
        volumes:
          - .:/app
        ports:
          - 3000:3000
            