import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { environment } from 'src/environments/environment';
import { Product } from '../model/product';
import { BaseService } from './base.service';

@Injectable({
  providedIn: 'root'
})
export class ProductService extends BaseService<Product> {

  listPlant: Product[] =

[
  /* {
    "Magyar név": null,
    "_id": null,
    "Elérhető": null,
    "Ár": 35,
    "Latin név": null,
    "Fényigény": "nap/árnyék",
    "Tenyészidő": "1 nyári/évelő",
    "Talajigény": "savanyú/meszes",
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  }, */
  {
    "Magyar név": "Tiszafa",
    "_id": "a1",
    "Elérhető": true,
    "Ár": 63,
    "Latin név": "Taxus Baccata",
    "Fényigény": "napos",
    "Tenyészidő": "évelő",
    "Talajigény": "normál",
    "Habitus": "fásszárú",
    "Teljes magasság": "15 m",
    "Kiszerelés": "5l konténer",
    "Virágzás ideje": "IV - V",
    "Virág színe": null,
    "Egyéb": "örökzöld, lassú növekedésű, akár 2000 évig is él, mérgező"
  },
  {
    "Magyar név": "Lilaakác",
    "_id": "b1",
    "Elérhető": true,
    "Ár": 22,
    "Latin név": "Wisteria Sinensis",
    "Fényigény": "napos",
    "Tenyészidő": "évelő",
    "Talajigény": "enyhén savas",
    "Habitus": "kúszó",
    "Teljes magasság": "8 -10 m",
    "Kiszerelés": "3l konténer",
    "Virágzás ideje": "IV",
    "Virág színe": "lila",
    "Egyéb": "gyors növekedésű, illatos, metszése szükséges, fiatalon fagyérzékeny"
  },
  {
    "Magyar név": "Páfrányfenyő",
    "_id": "a2",
    "Elérhető": true,
    "Ár": 36,
    "Latin név": "Ginko Biloba",
    "Fényigény": "napos",
    "Tenyészidő": "évelő",
    "Talajigény": "normál",
    "Habitus": "fásszárú",
    "Teljes magasság": "1ö - 12 m",
    "Kiszerelés": "5l konténer",
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": "lombhullató, fagytűtő, hímivarú növényt küldünk, ősszel sárgul"
  },
  {
    "Magyar név": "Mezei Juhar",
    "_id": "b2",
    "Elérhető": true,
    "Ár": 12,
    "Latin név": "Acer Campestre",
    "Fényigény": "napos",
    "Tenyészidő": "évelő",
    "Talajigény": "vályog, meszes",
    "Habitus": "fásszárú",
    "Teljes magasság": "15 m",
    "Kiszerelés": "5l konténer",
    "Virágzás ideje": "IV",
    "Virág színe": null,
    "Egyéb": "lombhullató, fagytűtő, ősszel sárgul"
  },
  {
    "Magyar név": "Japán Juhar piros",
    "_id": "a2",
    "Elérhető": true,
    "Ár": 27,
    "Latin név": "Acer Palmatum",
    "Fényigény": "félárnyék",
    "Tenyészidő": "évelő",
    "Talajigény": "enyhén savas",
    "Habitus": "fásszárú",
    "Teljes magasság": "1,5 m",
    "Kiszerelés": "3l konténer",
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": "lombhullató, fagytűrő, ősszel piroslik, dekoratív,"
  },
  {
    "Magyar név": "Korai Juhar",
    "_id": "b2",
    "Elérhető": true,
    "Ár": 23,
    "Latin név": "Acer Plantanoides",
    "Fényigény": "napos",
    "Tenyészidő": "évelő",
    "Talajigény": "meszes",
    "Habitus": "fásszárú",
    "Teljes magasság": "30 m",
    "Kiszerelés": "5l konténer",
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": "üde, nyírkos talajt kedveli, lombhullató, gyors növekedésű"
  },
  {
    "Magyar név": "Tatár Juhar",
    "_id": "a3",
    "Elérhető": true,
    "Ár": 95,
    "Latin név": "Acer Tataricum",
    "Fényigény": "napos",
    "Tenyészidő": "évelő",
    "Talajigény": "meszes",
    "Habitus": "fásszárú",
    "Teljes magasság": "10 m",
    "Kiszerelés": "5l konténer",
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": "300 évig is elél, szárazságtűrő, lombhullató, fagytűrő,"
  },
  {
    "Magyar név": "Sárga futórózsa",
    "_id": "b3",
    "Elérhető": true,
    "Ár": 85,
    "Latin név": "Rosa Adson von Melk",
    "Fényigény": "napos",
    "Tenyészidő": "évelő",
    "Talajigény": "normál",
    "Habitus": "cserje",
    "Teljes magasság": "1,5 - 2 m",
    "Kiszerelés": "3l konténer",
    "Virágzás ideje": "V - VII",
    "Virág színe": "sárga",
    "Egyéb": "erőteljes növekedésű, metszést igényel, diszkrét illatú, laza tápdús taljt kedvel"
  },
  {
    "Magyar név": "Parkrózsa",
    "_id": "a3",
    "Elérhető": false,
    "Ár": 58,
    "Latin név": "Rosa Raubritter",
    "Fényigény": "napos",
    "Tenyészidő": "évelő",
    "Talajigény": "normál",
    "Habitus": "cserje",
    "Teljes magasság": "50 - 60 cm",
    "Kiszerelés": "3l konténer",
    "Virágzás ideje": "V - VII",
    "Virág színe": "rózsaszín",
    "Egyéb": "laza tápdús taljt kedvel, dúsan virágzik"
  },
  {
    "Magyar név": "Törpe Rózsa",
    "_id": "b3",
    "Elérhető": true,
    "Ár": 61,
    "Latin név": "Rosa Ditroit",
    "Fényigény": "napos",
    "Tenyészidő": "évelő",
    "Talajigény": "normál",
    "Habitus": "cserje",
    "Teljes magasság": "25 - 30 cm",
    "Kiszerelés": "12 cm cserép",
    "Virágzás ideje": "V - VII",
    "Virág színe": "vörös",
    "Egyéb": "laza tápdús taljt kedvel, dúsan virágzik, metszést igényel"
  },
  {
    "Magyar név": "Tearózsa hibrid",
    "_id": "a4",
    "Elérhető": true,
    "Ár": 97,
    "Latin név": "Rosa Ariel",
    "Fényigény": "napos",
    "Tenyészidő": "évelő",
    "Talajigény": "normál",
    "Habitus": "cserje",
    "Teljes magasság": "60 - 80 cm",
    "Kiszerelés": "3l konténer",
    "Virágzás ideje": "V - VII",
    "Virág színe": "narancs",
    "Egyéb": "laza tápdús taljt kedvel, intenzív illatú, metszést igényel"
  },
  {
    "Magyar név": "Angol Rózsa",
    "_id": "b4",
    "Elérhető": true,
    "Ár": 62,
    "Latin név": "Rosa Ausvelvet",
    "Fényigény": "napos",
    "Tenyészidő": "évelő",
    "Talajigény": "normál",
    "Habitus": "cserje",
    "Teljes magasság": "60 - 80 cm",
    "Kiszerelés": "3l konténer",
    "Virágzás ideje": "V - VII",
    "Virág színe": "bíborlila",
    "Egyéb": "laza tápdús taljt kedvel, intenzív illatú, metszést igényel"
  },
  {
    "Magyar név": "Boglárka cserje",
    "_id": "a4",
    "Elérhető": true,
    "Ár": 83,
    "Latin név": "Kerria Japonica",
    "Fényigény": "félárnyék",
    "Tenyészidő": "évelő",
    "Talajigény": "normál",
    "Habitus": "cserje",
    "Teljes magasság": "2 -3 m",
    "Kiszerelés": "3l konténer",
    "Virágzás ideje": "IV -V",
    "Virág színe": "napsárga",
    "Egyéb": "kecses, lehajló ágú, jól terjed gyökérről, lombhullató"
  },
  {
    "Magyar név": "Mahónia",
    "_id": "b4",
    "Elérhető": true,
    "Ár": 22,
    "Latin név": "Mahonia Aquifolium",
    "Fényigény": "félárnyék",
    "Tenyészidő": "évelő",
    "Talajigény": "normál",
    "Habitus": "cserje",
    "Teljes magasság": "60 - 80 cm",
    "Kiszerelés": "3l konténer",
    "Virágzás ideje": "III",
    "Virág színe": "sárga",
    "Egyéb": "örökzöld, tüskésen fogas leveli szúrósak, szárazság tűrő, madarak kedvelik a bogyóját"
  },
  {
    "Magyar név": "Gyöngyikés Gyepliliom",
    "_id": "a5",
    "Elérhető": true,
    "Ár": 32,
    "Latin név": "Liriope muscari",
    "Fényigény": "félárnyék",
    "Tenyészidő": "évelő",
    "Talajigény": "enyhén savas",
    "Habitus": "lágyszárú",
    "Teljes magasság": "30 cm",
    "Kiszerelés": "12 cm cserép",
    "Virágzás ideje": "VIII - IX",
    "Virág színe": "liláskék",
    "Egyéb": "gyökérgumós, fagytűrő, rendkívül jól terjed,"
  },
  {
    "Magyar név": "Kis  télizöld meténg",
    "_id": "b5",
    "Elérhető": true,
    "Ár": 10,
    "Latin név": "Vinca Minor",
    "Fényigény": "félárnyék",
    "Tenyészidő": "évelő",
    "Talajigény": "normál",
    "Habitus": "lágyszárú",
    "Teljes magasság": "20 cm",
    "Kiszerelés": "12 cm cserép",
    "Virágzás ideje": "IV - V",
    "Virág színe": "liláskék",
    "Egyéb": "örökzöld, indákkal jól szaporodik, mérgező, vérnyomás csökkentő hatású"
  },
  {
    "Magyar név": "Tarka levelű nagymeténg",
    "_id": "a5",
    "Elérhető": true,
    "Ár": 24,
    "Latin név": "Vinca Major Variegata",
    "Fényigény": "félárnyék",
    "Tenyészidő": "évelő",
    "Talajigény": "normál",
    "Habitus": "lágyszárú",
    "Teljes magasság": "50 cm",
    "Kiszerelés": "12 cm cserép",
    "Virágzás ideje": "IV - V",
    "Virág színe": "liláskék",
    "Egyéb": "örökzöld, indákkal jól szaporodik, mérgező, vérnyomás csökkentő hatású"
  },
  {
    "Magyar név": "Pompás Hóvirág",
    "_id": "b5",
    "Elérhető": false,
    "Ár": 33,
    "Latin név": "Galanthus Elvesii",
    "Fényigény": "félárnyék",
    "Tenyészidő": "évelő",
    "Talajigény": "normál",
    "Habitus": "lágyszárú",
    "Teljes magasság": "20 cm",
    "Kiszerelés": "15 hagyma",
    "Virágzás ideje": "II - III",
    "Virág színe": "fehér",
    "Egyéb": "hagymás, de magról is jól terjed, ay első virágok egyike"
  },
  {
    "Magyar név": "Gyöngyvirág",
    "_id": "a6",
    "Elérhető": true,
    "Ár": 94,
    "Latin név": "Convallaria Majalis",
    "Fényigény": "árnyék",
    "Tenyészidő": "évelő",
    "Talajigény": "normál",
    "Habitus": "lágyszárú",
    "Teljes magasság": "20 cm",
    "Kiszerelés": "15 hagyma",
    "Virágzás ideje": "V",
    "Virág színe": "fehér",
    "Egyéb": "hagymás, illatos, nagyon mérgező"
  },
  {
    "Magyar név": "Jáccint",
    "_id": "b6",
    "Elérhető": true,
    "Ár": 66,
    "Latin név": "Hyacintus Orientalis",
    "Fényigény": "napos",
    "Tenyészidő": "évelő",
    "Talajigény": "normál",
    "Habitus": "lágyszárú",
    "Teljes magasság": "25 cm",
    "Kiszerelés": "3 hagyma",
    "Virágzás ideje": "IV",
    "Virág színe": "vegyes",
    "Egyéb": "hagymás, nagyon illatos, cserépben is nevelhető, nagyon mérgező, kevés viyet igényel"
  },
  {
    "Magyar név": "Díszhagyma",
    "_id": "a6",
    "Elérhető": true,
    "Ár": 79,
    "Latin név": "Allium Giganteum",
    "Fényigény": "napos",
    "Tenyészidő": "évelő",
    "Talajigény": "normál",
    "Habitus": "lágyszárú",
    "Teljes magasság": "80 cm",
    "Kiszerelés": "5 hagyma",
    "Virágzás ideje": "V",
    "Virág színe": "lila",
    "Egyéb": "hagymés, mérsékelt vízigényű, egyszerű gondozni"
  },
  {
    "Magyar név": "Sáfrány variánsok",
    "_id": "b6",
    "Elérhető": true,
    "Ár": 50,
    "Latin név": "Crocus Vernus",
    "Fényigény": "napos",
    "Tenyészidő": "évelő",
    "Talajigény": "meszes",
    "Habitus": "lágyszárú",
    "Teljes magasság": "15 cm",
    "Kiszerelés": "20 hagyma",
    "Virágzás ideje": "III - IV",
    "Virág színe": "vegyes",
    "Egyéb": "hagymás, szárazság tűrő, nagyvirágú, koratavaszi"
  },
  {
    "Magyar név": "Méhbalzsam",
    "_id": "a7",
    "Elérhető": true,
    "Ár": 67,
    "Latin név": "Monarda Fistulosa",
    "Fényigény": "napos",
    "Tenyészidő": "évelő",
    "Talajigény": "homokos",
    "Habitus": "lágyszárú",
    "Teljes magasság": "30 cm",
    "Kiszerelés": "12 cm cserép",
    "Virágzás ideje": "VII",
    "Virág színe": "bíborlila",
    "Egyéb": "fűszeres illatú, gyógyhatású, limonádéba kellemes aromát ad, tőosztással szaporítható"
  },
  {
    "Magyar név": "Kontyvirág",
    "_id": "b7",
    "Elérhető": true,
    "Ár": 33,
    "Latin név": "Arum Maculatum",
    "Fényigény": "félárnyék",
    "Tenyészidő": "évelő",
    "Talajigény": "enyhén savas",
    "Habitus": "lágyszárú",
    "Teljes magasság": "40 cm",
    "Kiszerelés": "1 rizóma",
    "Virágzás ideje": "IV",
    "Virág színe": "zöld",
    "Egyéb": "nedves környezetet kedveli, bogyói jól díszítenek, mérgező"
  },
  {
    "Magyar név": "Sárkány kontyvirág",
    "_id": "a7",
    "Elérhető": true,
    "Ár": 88,
    "Latin név": "Dracunculus vulgaris",
    "Fényigény": "félárnyék",
    "Tenyészidő": "évelő",
    "Talajigény": "enyhén savas",
    "Habitus": "lágyszárú",
    "Teljes magasság": "80 cm",
    "Kiszerelés": "1 hagyma",
    "Virágzás ideje": "V",
    "Virág színe": "vörös",
    "Egyéb": "akár 20 évig is él, rendkívüli hatalmas virágai 70 - 80 cmt is elérheti, mérsékelt víigényű"
  },
  {
    "Magyar név": "Züld Tűzeső",
    "_id": "b7",
    "Elérhető": true,
    "Ár": 33,
    "Latin név": "Heuchera sanguinea",
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Bordó Tűzeső",
    "_id": "a8",
    "Elérhető": false,
    "Ár": 78,
    "Latin név": "Heuchera micrantha",
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Szártalan kankalin",
    "_id": "b8",
    "Elérhető": true,
    "Ár": 71,
    "Latin név": "Primrose",
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Liliomfa sötétrózsaszín",
    "_id": "a8",
    "Elérhető": true,
    "Ár": 23,
    "Latin név": "Magnolia Randy",
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Liliomfa illatos",
    "_id": "b8",
    "Elérhető": true,
    "Ár": 92,
    "Latin név": "Magnolia Fragrant",
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Madársóska",
    "_id": "a9",
    "Elérhető": true,
    "Ár": 16,
    "Latin név": "Oxalis",
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Tündérvirág",
    "_id": "b9",
    "Elérhető": true,
    "Ár": 31,
    "Latin név": "Epimedium perralchicum",
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Téltemető",
    "_id": "a9",
    "Elérhető": true,
    "Ár": 31,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Odvas keltike",
    "_id": "b9",
    "Elérhető": true,
    "Ár": 79,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Csíkos Árnyékliliom",
    "_id": "a10",
    "Elérhető": true,
    "Ár": 1,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Oriás Árnyékliliom",
    "_id": "b10",
    "Elérhető": false,
    "Ár": 33,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Medvehagyma",
    "_id": "a10",
    "Elérhető": true,
    "Ár": 68,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Pettyegetett Tüdőfü",
    "_id": "b10",
    "Elérhető": true,
    "Ár": 80,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Dunavölgyi Csillagvirág",
    "_id": "a11",
    "Elérhető": true,
    "Ár": 52,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Erdei Ciklámen",
    "_id": "b11",
    "Elérhető": true,
    "Ár": 38,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Salamonpecsét",
    "_id": "a11",
    "Elérhető": true,
    "Ár": 79,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Illatos Hunyor",
    "_id": "b11",
    "Elérhető": true,
    "Ár": 3,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Pirosló Hunyor",
    "_id": "a12",
    "Elérhető": true,
    "Ár": 83,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Zöld Hunyor",
    "_id": "b12",
    "Elérhető": true,
    "Ár": 86,
    "Latin név": "Helleborus Viridis",
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Erdei Pajzsika",
    "_id": "a12",
    "Elérhető": false,
    "Ár": 85,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Harangláb",
    "_id": "b12",
    "Elérhető": true,
    "Ár": 91,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Fürtös Gyöngyike",
    "_id": "a13",
    "Elérhető": true,
    "Ár": 27,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Bőrlevél",
    "_id": "b13",
    "Elérhető": true,
    "Ár": 7,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Szívvirág",
    "_id": "a13",
    "Elérhető": true,
    "Ár": 51,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Csatavirág",
    "_id": "b13",
    "Elérhető": true,
    "Ár": 1,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Japán Kecskerágó",
    "_id": "a14",
    "Elérhető": true,
    "Ár": 66,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Orbáncfű cserje",
    "_id": "b14",
    "Elérhető": true,
    "Ár": 59,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Redős Bangita",
    "_id": "a14",
    "Elérhető": true,
    "Ár": 49,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Kikeleti Bangita",
    "_id": "b14",
    "Elérhető": false,
    "Ár": 77,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Arany törpetuja",
    "_id": "a15",
    "Elérhető": true,
    "Ár": 48,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Gyöngyvirág cserje",
    "_id": "b15",
    "Elérhető": true,
    "Ár": 37,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Nyuszifül",
    "_id": "a15",
    "Elérhető": true,
    "Ár": 21,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Kamcsatkai Mézbogyó",
    "_id": "b15",
    "Elérhető": true,
    "Ár": 1,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Csillagfürt",
    "_id": "a16",
    "Elérhető": true,
    "Ár": 27,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Gumós Begónia oriás",
    "_id": "b16",
    "Elérhető": true,
    "Ár": 25,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Gumós Begónia csüngő",
    "_id": "a16",
    "Elérhető": true,
    "Ár": 8,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Törpe Begónia",
    "_id": "b16",
    "Elérhető": true,
    "Ár": 48,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Bordó Sóskaborbolya",
    "_id": "a17",
    "Elérhető": false,
    "Ár": 83,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Tűzliliom",
    "_id": "b17",
    "Elérhető": true,
    "Ár": 79,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Nárcisz",
    "_id": "a17",
    "Elérhető": true,
    "Ár": 0,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Babarózsa",
    "_id": "b17",
    "Elérhető": true,
    "Ár": 14,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Csodatölcsér",
    "_id": "a18",
    "Elérhető": true,
    "Ár": 48,
    "Latin név": "Mirabilis",
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Ólomvirág",
    "_id": "b18",
    "Elérhető": true,
    "Ár": 47,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Gömb tuja",
    "_id": "a18",
    "Elérhető": true,
    "Ár": 44,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Lucfenyő",
    "_id": "b18",
    "Elérhető": true,
    "Ár": 43,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Bazsarózsa",
    "_id": "a19",
    "Elérhető": true,
    "Ár": 90,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Labda Hortenzia",
    "_id": "b19",
    "Elérhető": false,
    "Ár": 77,
    "Latin név": "Hydrangea Macrophyla",
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Fűrészes levelű Hortenzia",
    "_id": "a19",
    "Elérhető": true,
    "Ár": 28,
    "Latin név": "Hydrangea Serrata",
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Kínai lilabogyó",
    "_id": "b19",
    "Elérhető": true,
    "Ár": 1,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Közönséges Nyír",
    "_id": "a20",
    "Elérhető": true,
    "Ár": 53,
    "Latin név": "Betula Pendula",
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Táskavirág",
    "_id": "b20",
    "Elérhető": true,
    "Ár": 38,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Prérigyertya",
    "_id": "a20",
    "Elérhető": true,
    "Ár": 41,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Cserszömörce",
    "_id": "b20",
    "Elérhető": true,
    "Ár": 63,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Nagylevelű Hárs",
    "_id": "a21",
    "Elérhető": true,
    "Ár": 28,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Kislevelű Hárs",
    "_id": "b21",
    "Elérhető": true,
    "Ár": 6,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Jezsámen",
    "_id": "a21",
    "Elérhető": false,
    "Ár": 31,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Kék Babfa",
    "_id": "b21",
    "Elérhető": true,
    "Ár": 38,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Piros Gyűszűvirág",
    "_id": "a22",
    "Elérhető": true,
    "Ár": 61,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Kaukázusi Nefelejcs",
    "_id": "b22",
    "Elérhető": true,
    "Ár": 72,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Nagylevelű Nefelejcs",
    "_id": "a22",
    "Elérhető": true,
    "Ár": 18,
    "Latin név": "Brunnera Macrophylla",
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Nagyvirágú Gólyaorr",
    "_id": "b22",
    "Elérhető": true,
    "Ár": 48,
    "Latin név": "Geranium Sanguineum",
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Kék Gólyaorr",
    "_id": "a23",
    "Elérhető": true,
    "Ár": 74,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Himalájai Gólyaorr",
    "_id": "b23",
    "Elérhető": true,
    "Ár": 22,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Viking Feketeberkenye",
    "_id": "a23",
    "Elérhető": true,
    "Ár": 0,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Piros Ribizli",
    "_id": "b23",
    "Elérhető": false,
    "Ár": 87,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Tüskétlen Szeder",
    "_id": "a24",
    "Elérhető": true,
    "Ár": 33,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Pallagi Egres",
    "_id": "b24",
    "Elérhető": true,
    "Ár": 0,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Fertődi zamatos Málna",
    "_id": "a24",
    "Elérhető": true,
    "Ár": 99,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Fekete Bodza",
    "_id": "b24",
    "Elérhető": true,
    "Ár": 24,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Illatos Orgona",
    "_id": "a25",
    "Elérhető": true,
    "Ár": 61,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Amerikai Futólonc",
    "_id": "b25",
    "Elérhető": true,
    "Ár": 15,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Illatos Futólonc",
    "_id": "a25",
    "Elérhető": true,
    "Ár": 80,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Ringlószilva",
    "_id": "b25",
    "Elérhető": true,
    "Ár": 0,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Füge",
    "_id": "a26",
    "Elérhető": false,
    "Ár": 84,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Madárbirs",
    "_id": "b26",
    "Elérhető": true,
    "Ár": 64,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Yucca",
    "_id": "a26",
    "Elérhető": true,
    "Ár": 22,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Palmeri Varjúháj",
    "_id": "b26",
    "Elérhető": true,
    "Ár": 50,
    "Latin név": "Sedum Palmeri",
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Borsos Varjúháj",
    "_id": "a27",
    "Elérhető": true,
    "Ár": 13,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": null,
    "_id": "b27",
    "Elérhető": true,
    "Ár": 58,
    "Latin név": "Sedum ternatum",
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": null,
    "_id": "a27",
    "Elérhető": true,
    "Ár": 76,
    "Latin név": "Armeria maritima",
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": null,
    "_id": "b27",
    "Elérhető": true,
    "Ár": 8,
    "Latin név": "Saxifraga callosa",
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": null,
    "_id": "a28",
    "Elérhető": true,
    "Ár": 12,
    "Latin név": "Sempervivum Tectorum",
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": null,
    "_id": "b28",
    "Elérhető": false,
    "Ár": 8,
    "Latin név": "Sempervivum Montanum",
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": null,
    "_id": "a28",
    "Elérhető": true,
    "Ár": 11,
    "Latin név": "Hebe Andesonii",
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": null,
    "_id": "b28",
    "Elérhető": true,
    "Ár": 40,
    "Latin név": "Euphorbia Myrsinites",
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Hasindító Kutyatej",
    "_id": "a29",
    "Elérhető": true,
    "Ár": 27,
    "Latin név": "Euphorbia Lathyris",
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": null,
    "_id": "b29",
    "Elérhető": true,
    "Ár": 71,
    "Latin név": "Sedum Spurium",
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": null,
    "_id": "a29",
    "Elérhető": true,
    "Ár": 29,
    "Latin név": "Sedum Rupestre",
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Dalmát Harangvirág",
    "_id": "b29",
    "Elérhető": true,
    "Ár": 69,
    "Latin név": "Campanula Portenschlagiana",
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Pettyes harangvirág",
    "_id": "a30",
    "Elérhető": true,
    "Ár": 49,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Csüngő Harangvirág",
    "_id": "b30",
    "Elérhető": true,
    "Ár": 32,
    "Latin név": "Campanula Pposcharskyana",
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Baracklevelű Harangvirág",
    "_id": "a30",
    "Elérhető": false,
    "Ár": 64,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Közönséges Kökörcsin",
    "_id": "b30",
    "Elérhető": true,
    "Ár": 49,
    "Latin név": "Pusatilla Vulgaris",
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Vöröstölgy",
    "_id": "a31",
    "Elérhető": true,
    "Ár": 63,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "CsászárTölgy",
    "_id": "b31",
    "Elérhető": true,
    "Ár": 48,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Kocsányos Tölgy",
    "_id": "a31",
    "Elérhető": true,
    "Ár": 8,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Virágos Kőris",
    "_id": "b31",
    "Elérhető": true,
    "Ár": 94,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Oszlopos Gyertyán",
    "_id": "a32",
    "Elérhető": true,
    "Ár": 43,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Kínai Galagonya",
    "_id": "b32",
    "Elérhető": true,
    "Ár": 39,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Egybibés galagonya",
    "_id": "a32",
    "Elérhető": true,
    "Ár": 24,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Mogyoró",
    "_id": "b32",
    "Elérhető": false,
    "Ár": 34,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Hósos Som",
    "_id": "a33",
    "Elérhető": true,
    "Ár": 99,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Veresgyűrűs som",
    "_id": "b33",
    "Elérhető": true,
    "Ár": 22,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Mocsári Hibiscus",
    "_id": "a33",
    "Elérhető": true,
    "Ár": 20,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Fekete Mályva",
    "_id": "b33",
    "Elérhető": true,
    "Ár": 59,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Mályva cserje",
    "_id": "a34",
    "Elérhető": true,
    "Ár": 33,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Japán kövérke",
    "_id": "b34",
    "Elérhető": true,
    "Ár": 68,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Méyontófű",
    "_id": "a34",
    "Elérhető": true,
    "Ár": 49,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Nagyvirágó Laputurbolza",
    "_id": "b34",
    "Elérhető": true,
    "Ár": 38,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Levendula",
    "_id": "a35",
    "Elérhető": false,
    "Ár": 89,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Rozmaring",
    "_id": "b35",
    "Elérhető": true,
    "Ár": 68,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Kerti Kaukkfű",
    "_id": "a35",
    "Elérhető": true,
    "Ár": 37,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Mezei Kakukkfű",
    "_id": "b35",
    "Elérhető": true,
    "Ár": 69,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Zsálya",
    "_id": "a36",
    "Elérhető": true,
    "Ár": 59,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Majoranna",
    "_id": "b36",
    "Elérhető": true,
    "Ár": 14,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Szurokfű",
    "_id": "a36",
    "Elérhető": true,
    "Ár": 92,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Citromfű",
    "_id": "b36",
    "Elérhető": true,
    "Ár": 54,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Fodormenta",
    "_id": "a37",
    "Elérhető": true,
    "Ár": 28,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Borsmenta",
    "_id": "b37",
    "Elérhető": false,
    "Ár": 54,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Cickafark",
    "_id": "a37",
    "Elérhető": true,
    "Ár": 89,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Lándzsás utifű",
    "_id": "b37",
    "Elérhető": true,
    "Ár": 57,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Széleslevelű utifű",
    "_id": "a38",
    "Elérhető": true,
    "Ár": 29,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Százszorszép",
    "_id": "b38",
    "Elérhető": true,
    "Ár": 81,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Kányazsombor",
    "_id": "a38",
    "Elérhető": true,
    "Ár": 44,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Vérehulló Fecskefű",
    "_id": "b38",
    "Elérhető": true,
    "Ár": 79,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Fekete nadálytő",
    "_id": "a39",
    "Elérhető": true,
    "Ár": 1,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Sárgaárvacsalán",
    "_id": "b39",
    "Elérhető": true,
    "Ár": 3,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Vörösárvacsalán",
    "_id": "a39",
    "Elérhető": false,
    "Ár": 86,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Havasi ligetszépe",
    "_id": "b39",
    "Elérhető": true,
    "Ár": 7,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Díszpipacs",
    "_id": "a40",
    "Elérhető": true,
    "Ár": 40,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Vöröshere",
    "_id": "b40",
    "Elérhető": true,
    "Ár": 14,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Fehérhere",
    "_id": "a40",
    "Elérhető": true,
    "Ár": 26,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Mángold",
    "_id": "b40",
    "Elérhető": true,
    "Ár": 41,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Vöröserű Sóska",
    "_id": "a41",
    "Elérhető": true,
    "Ár": 84,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Rebarbara",
    "_id": "b41",
    "Elérhető": true,
    "Ár": 23,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Erika",
    "_id": "a41",
    "Elérhető": true,
    "Ár": 45,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Leander",
    "_id": "b41",
    "Elérhető": false,
    "Ár": 38,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Közönséges Borostyán",
    "_id": "a42",
    "Elérhető": true,
    "Ár": 20,
    "Latin név": "Hedera helix",
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Tarka Borostyán",
    "_id": "b42",
    "Elérhető": true,
    "Ár": 11,
    "Latin név": "Hedera Algeriensis",
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Erdei Szellőrózsa",
    "_id": "a42",
    "Elérhető": true,
    "Ár": 12,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Vadgesztenye",
    "_id": "b42",
    "Elérhető": true,
    "Ár": 78,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Csörgőfa",
    "_id": "a43",
    "Elérhető": true,
    "Ár": 17,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Tulipán variációk",
    "_id": "b43",
    "Elérhető": true,
    "Ár": 21,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Fehér Akác",
    "_id": "a43",
    "Elérhető": true,
    "Ár": 52,
    "Latin név": null,
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Árlevelű lángvirág",
    "_id": "b43",
    "Elérhető": true,
    "Ár": 4,
    "Latin név": "Phlox Subulata",
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  },
  {
    "Magyar név": "Bugás Lángvirág",
    "_id": "a44",
    "Elérhető": false,
    "Ár": 23,
    "Latin név": "Phlox Paniculata",
    "Fényigény": null,
    "Tenyészidő": null,
    "Talajigény": null,
    "Habitus": null,
    "Teljes magasság": null,
    "Kiszerelés": null,
    "Virágzás ideje": null,
    "Virág színe": null,
    "Egyéb": null
  }
]


  list: Product[] = [
    {
      _id: '12234dklfsjs',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '3434jlkjlkj43l4',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '434325423542354lkjljlk',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: 'jfdslfkjsdlkjf325432423',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '12234dklfsjs',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '3434jlkjlkj43l4',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '434325423542354lkjljlk',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: 'jfdslfkjsdlkjf325432423',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '12234dklfsjs',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '3434jlkjlkj43l4',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '434325423542354lkjljlk',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: 'jfdslfkjsdlkjf325432423',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '12234dklfsjs',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '3434jlkjlkj43l4',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '434325423542354lkjljlk',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: 'jfdslfkjsdlkjf325432423',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '12234dklfsjs',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '3434jlkjlkj43l4',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '434325423542354lkjljlk',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: 'jfdslfkjsdlkjf325432423',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '12234dklfsjs',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '3434jlkjlkj43l4',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '434325423542354lkjljlk',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: 'jfdslfkjsdlkjf325432423',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '3434jlkjlkj43l4',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '434325423542354lkjljlk',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: 'jfdslfkjsdlkjf325432423',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '3434jlkjlkj43l4',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '434325423542354lkjljlk',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: 'jfdslfkjsdlkjf325432423',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '3434jlkjlkj43l4',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '434325423542354lkjljlk',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: 'jfdslfkjsdlkjf325432423',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
  ];

  constructor(
    public override http: HttpClient
  ) {
    super(http);
    this.entityName = 'product';
   }

  override getAll(): Observable<Product[]> {
    // return this.http.get<Product[]>(`${this.apiUrl}product`);
    return of(this.listPlant);
  }

}
