import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { environment } from 'src/environments/environment';
import { Product } from '../model/product';

@Injectable({
  providedIn: 'root'
})
export class ProductService {

  /* list: Product[] =
  [
    {
      "Magyar név": null,
      "Latin név": null,
      "Fényigény": "nap/árnyék",
      "Tenyészidő": "1 nyári/évelő",
      "Talajigény": "savanyú/meszes",
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Tiszafa",
      "Latin név": "Taxus Baccata",
      "Fényigény": "napos",
      "Tenyészidő": "évelő",
      "Talajigény": "normál",
      "Habitus": "fásszárú",
      "Teljes magasság": "15 m",
      "Kiszerelés": "5l konténer",
      "Virágzás ideje": "IV - V",
      "Virág színe": null,
      "Egyéb": "örökzöld, lassú növekedésű, akár 2öö évig is él, mérgező"
    },
    {
      "Magyar név": "Lilaakác",
      "Latin név": "Wisteria Sinensis",
      "Fényigény": "napos",
      "Tenyészidő": "évelő",
      "Talajigény": "enyhén savas",
      "Habitus": "kúszó",
      "Teljes magasság": "8 -10 m",
      "Kiszerelés": "3l konténer",
      "Virágzás ideje": "IV",
      "Virág színe": "lila",
      "Egyéb": "gyors növekedésű, illatos, metszése szükséges, fiatalon fagyérzékeny"
    },
    {
      "Magyar név": "Páfrányfenyő",
      "Latin név": "Ginko Biloba",
      "Fényigény": "napos",
      "Tenyészidő": "évelő",
      "Talajigény": "normál",
      "Habitus": "fásszárú",
      "Teljes magasság": "1ö - 12 m",
      "Kiszerelés": "5l konténer",
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": "lombhullató, fagytűtő, hímivarú növényt küldünk, ősszel sárgul"
    },
    {
      "Magyar név": "Mezei Juhar",
      "Latin név": "Acer Campestre",
      "Fényigény": "napos",
      "Tenyészidő": "évelő",
      "Talajigény": "vályog, meszes",
      "Habitus": "fásszárú",
      "Teljes magasság": "15 m",
      "Kiszerelés": "5l konténer",
      "Virágzás ideje": "IV",
      "Virág színe": null,
      "Egyéb": "lombhullató, fagytűtő, ősszel sárgul"
    },
    {
      "Magyar név": "Japán Juhar piros",
      "Latin név": "Acer Palmatum",
      "Fényigény": "félárnyék",
      "Tenyészidő": "évelő",
      "Talajigény": "enyhén savas",
      "Habitus": "fásszárú",
      "Teljes magasság": "1,5 m",
      "Kiszerelés": "3l konténer",
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": "lombhullató, fagytűrő, ősszel piroslik, dekoratív,"
    },
    {
      "Magyar név": "Korai Juhar",
      "Latin név": "Acer Plantanoides",
      "Fényigény": "napos",
      "Tenyészidő": "évelő",
      "Talajigény": "meszes",
      "Habitus": "fásszárú",
      "Teljes magasság": "30 m",
      "Kiszerelés": "5l konténer",
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": "üde, nyírkos talajt kedveli, lombhullató, gyors növekedésű"
    },
    {
      "Magyar név": "Tatár Juhar",
      "Latin név": "Acer Tataricum",
      "Fényigény": "napos",
      "Tenyészidő": "évelő",
      "Talajigény": "meszes",
      "Habitus": "fásszárú",
      "Teljes magasság": "10 m",
      "Kiszerelés": "5l konténer",
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": "300 évig is elél, szárazságtűrő, lombhullató, fagytűrő,"
    },
    {
      "Magyar név": "Sárga futórózsa",
      "Latin név": "Rosa Adson von Melk",
      "Fényigény": "napos",
      "Tenyészidő": "évelő",
      "Talajigény": "normál",
      "Habitus": "cserje",
      "Teljes magasság": "1,5 - 2 m",
      "Kiszerelés": "3l konténer",
      "Virágzás ideje": "V - VII",
      "Virág színe": "sárga",
      "Egyéb": "erőteljes növekedésű, metszést igényel, diszkrét illatú, laza tápdús taljt kedvel"
    },
    {
      "Magyar név": "Parkrózsa",
      "Latin név": "Rosa Raubritter",
      "Fényigény": "napos",
      "Tenyészidő": "évelő",
      "Talajigény": "normál",
      "Habitus": "cserje",
      "Teljes magasság": "50 - 60 cm",
      "Kiszerelés": "3l konténer",
      "Virágzás ideje": "V - VII",
      "Virág színe": "rózsaszín",
      "Egyéb": "laza tápdús taljt kedvel, dúsan virágzik"
    },
    {
      "Magyar név": "Törpe Rózsa",
      "Latin név": "Rosa Ditroit",
      "Fényigény": "napos",
      "Tenyészidő": "évelő",
      "Talajigény": "normál",
      "Habitus": "cserje",
      "Teljes magasság": "25 - 30 cm",
      "Kiszerelés": "12 cm cserép",
      "Virágzás ideje": "V - VII",
      "Virág színe": "vörös",
      "Egyéb": "laza tápdús taljt kedvel, dúsan virágzik, metszést igényel"
    },
    {
      "Magyar név": "Tearózsa hibrid",
      "Latin név": "Rosa Ariel",
      "Fényigény": "napos",
      "Tenyészidő": "évelő",
      "Talajigény": "normál",
      "Habitus": "cserje",
      "Teljes magasság": "60 - 80 cm",
      "Kiszerelés": "3l konténer",
      "Virágzás ideje": "V - VII",
      "Virág színe": "narancs",
      "Egyéb": "laza tápdús taljt kedvel, intenzív illatú, metszést igényel"
    },
    {
      "Magyar név": "Angol Rózsa",
      "Latin név": "Rosa Ausvelvet",
      "Fényigény": "napos",
      "Tenyészidő": "évelő",
      "Talajigény": "normál",
      "Habitus": "cserje",
      "Teljes magasság": "60 - 80 cm",
      "Kiszerelés": "3l konténer",
      "Virágzás ideje": "V - VII",
      "Virág színe": "bíborlila",
      "Egyéb": "laza tápdús taljt kedvel, intenzív illatú, metszést igényel"
    },
    {
      "Magyar név": "Boglárka cserje",
      "Latin név": "Kerria Japonica",
      "Fényigény": "félárnyék",
      "Tenyészidő": "évelő",
      "Talajigény": "normál",
      "Habitus": "cserje",
      "Teljes magasság": "2 -3 m",
      "Kiszerelés": "3l konténer",
      "Virágzás ideje": "IV -V",
      "Virág színe": "napsárga",
      "Egyéb": "kecses, lehajló ágú, jól terjed gyökérről, lombhullató"
    },
    {
      "Magyar név": "Mahónia",
      "Latin név": "Mahonia Aquifolium",
      "Fényigény": "félárnyék",
      "Tenyészidő": "évelő",
      "Talajigény": "normál",
      "Habitus": "cserje",
      "Teljes magasság": "60 - 80 cm",
      "Kiszerelés": "3l konténer",
      "Virágzás ideje": "III",
      "Virág színe": "sárga",
      "Egyéb": "örökzöld, tüskésen fogas leveli szúrósak, szárazság tűrő, madarak kedvelik a bogyóját"
    },
    {
      "Magyar név": "Gyöngyikés Gyepliliom",
      "Latin név": "Liriope muscari",
      "Fényigény": "félárnyék",
      "Tenyészidő": "évelő",
      "Talajigény": "enyhén savas",
      "Habitus": "lágyszárú",
      "Teljes magasság": "30 cm",
      "Kiszerelés": "12 cm cserép",
      "Virágzás ideje": "VIII - IX",
      "Virág színe": "liláskék",
      "Egyéb": "gyökérgumós, fagytűrő, rendkívül jól terjed,"
    },
    {
      "Magyar név": "Kis  télizöld meténg",
      "Latin név": "Vinca Minor",
      "Fényigény": "félárnyék",
      "Tenyészidő": "évelő",
      "Talajigény": "normál",
      "Habitus": "lágyszárú",
      "Teljes magasság": "20 cm",
      "Kiszerelés": "12 cm cserép",
      "Virágzás ideje": "IV - V",
      "Virág színe": "liláskék",
      "Egyéb": "örökzöld, indákkal jól szaporodik, mérgező, vérnyomás csökkentő hatású"
    },
    {
      "Magyar név": "Tarka levelű nagymeténg",
      "Latin név": "Vinca Major Variegata",
      "Fényigény": "félárnyék",
      "Tenyészidő": "évelő",
      "Talajigény": "normál",
      "Habitus": "lágyszárú",
      "Teljes magasság": "50 cm",
      "Kiszerelés": "12 cm cserép",
      "Virágzás ideje": "IV - V",
      "Virág színe": "liláskék",
      "Egyéb": "örökzöld, indákkal jól szaporodik, mérgező, vérnyomás csökkentő hatású"
    },
    {
      "Magyar név": "Pompás Hóvirág",
      "Latin név": "Galanthus Elvesii",
      "Fényigény": "félárnyék",
      "Tenyészidő": "évelő",
      "Talajigény": "normál",
      "Habitus": "lágyszárú",
      "Teljes magasság": "20 cm",
      "Kiszerelés": "15 hagyma",
      "Virágzás ideje": "II - III",
      "Virág színe": "fehér",
      "Egyéb": "hagymás, de magról is jól terjed, ay első virágok egyike"
    },
    {
      "Magyar név": "Gyöngyvirág",
      "Latin név": "Convallaria Majalis",
      "Fényigény": "árnyék",
      "Tenyészidő": "évelő",
      "Talajigény": "normál",
      "Habitus": "lágyszárú",
      "Teljes magasság": "20 cm",
      "Kiszerelés": "15 hagyma",
      "Virágzás ideje": "V",
      "Virág színe": "fehér",
      "Egyéb": "hagymás, illatos, nagyon mérgező"
    },
    {
      "Magyar név": "Jáccint",
      "Latin név": "Hyacintus Orientalis",
      "Fényigény": "napos",
      "Tenyészidő": "évelő",
      "Talajigény": "normál",
      "Habitus": "lágyszárú",
      "Teljes magasság": "25 cm",
      "Kiszerelés": "3 hagyma",
      "Virágzás ideje": "IV",
      "Virág színe": "vegyes",
      "Egyéb": "hagymás, nagyon illatos, cserépben is nevelhető, nagyon mérgező, kevés viyet igényel"
    },
    {
      "Magyar név": "Díszhagyma",
      "Latin név": "Allium Giganteum",
      "Fényigény": "napos",
      "Tenyészidő": "évelő",
      "Talajigény": "normál",
      "Habitus": "lágyszárú",
      "Teljes magasság": "80 cm",
      "Kiszerelés": "5 hagyma",
      "Virágzás ideje": "V",
      "Virág színe": "lila",
      "Egyéb": "hagymés, mérsékelt vízigényű, egyszerű gondozni"
    },
    {
      "Magyar név": "Sáfrány variánsok",
      "Latin név": "Crocus Vernus",
      "Fényigény": "napos",
      "Tenyészidő": "évelő",
      "Talajigény": "meszes",
      "Habitus": "lágyszárú",
      "Teljes magasság": "15 cm",
      "Kiszerelés": "20 hagyma",
      "Virágzás ideje": "III - IV",
      "Virág színe": "vegyes",
      "Egyéb": "hagymás, szárazság tűrő, nagyvirágú, koratavaszi"
    },
    {
      "Magyar név": "Méhbalzsam",
      "Latin név": "Monarda Fistulosa",
      "Fényigény": "napos",
      "Tenyészidő": "évelő",
      "Talajigény": "homokos",
      "Habitus": "lágyszárú",
      "Teljes magasság": "30 cm",
      "Kiszerelés": "12 cm cserép",
      "Virágzás ideje": "VII",
      "Virág színe": "bíborlila",
      "Egyéb": "fűszeres illatú, gyógyhatású, limonádéba kellemes aromát ad, tőosztással szaporítható"
    },
    {
      "Magyar név": "Kontyvirág",
      "Latin név": "Arum Maculatum",
      "Fényigény": "félárnyék",
      "Tenyészidő": "évelő",
      "Talajigény": "enyhén savas",
      "Habitus": "lágyszárú",
      "Teljes magasság": "40 cm",
      "Kiszerelés": "1 rizóma",
      "Virágzás ideje": "IV",
      "Virág színe": "zöld",
      "Egyéb": "nedves környezetet kedveli, bogyói jól díszítenek, mérgező"
    },
    {
      "Magyar név": "Sárkány kontyvirág",
      "Latin név": "Dracunculus vulgaris",
      "Fényigény": "félárnyék",
      "Tenyészidő": "évelő",
      "Talajigény": "enyhén savas",
      "Habitus": "lágyszárú",
      "Teljes magasság": "80 cm",
      "Kiszerelés": "1 hagyma",
      "Virágzás ideje": "V",
      "Virág színe": "vörös",
      "Egyéb": "akár 20 évig is él, rendkívüli hatalmas virágai 70 - 80 cmt is elérheti, mérsékelt víigényű"
    },
    {
      "Magyar név": "Züld Tűzeső",
      "Latin név": "Heuchera sanguinea",
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Bordó Tűzeső",
      "Latin név": "Heuchera micrantha",
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Szártalan kankalin",
      "Latin név": "Primrose",
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Liliomfa sötétrózsaszín",
      "Latin név": "Magnolia Randy",
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Liliomfa illatos",
      "Latin név": "Magnolia Fragrant",
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Madársóska",
      "Latin név": "Oxalis",
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Tündérvirág",
      "Latin név": "Epimedium perralchicum",
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Téltemető",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Odvas keltike",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Csíkos Árnyékliliom",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Oriás Árnyékliliom",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Medvehagyma",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Pettyegetett Tüdőfü",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Dunavölgyi Csillagvirág",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Erdei Ciklámen",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Salamonpecsét",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Illatos Hunyor",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Pirosló Hunyor",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Zöld Hunyor",
      "Latin név": "Helleborus Viridis",
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Erdei Pajzsika",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Harangláb",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Fürtös Gyöngyike",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Bőrlevél",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Szívvirág",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Csatavirág",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Japán Kecskerágó",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Orbáncfű cserje",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Redős Bangita",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Kikeleti Bangita",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Arany törpetuja",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Gyöngyvirág cserje",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Nyuszifül",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Kamcsatkai Mézbogyó",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Csillagfürt",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Gumós Begónia oriás",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Gumós Begónia csüngő",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Törpe Begónia",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Bordó Sóskaborbolya",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Tűzliliom",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Nárcisz",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Babarózsa",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Csodatölcsér",
      "Latin név": "Mirabilis",
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Ólomvirág",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Gömb tuja",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Lucfenyő",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Bazsarózsa",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Labda Hortenzia",
      "Latin név": "Hydrangea Macrophyla",
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Fűrészes levelű Hortenzia",
      "Latin név": "Hydrangea Serrata",
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Kínai lilabogyó",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Közönséges Nyír",
      "Latin név": "Betula Pendula",
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Táskavirág",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Prérigyertya",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Cserszömörce",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Nagylevelű Hárs",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Kislevelű Hárs",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Jezsámen",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Kék Babfa",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Piros Gyűszűvirág",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Kaukázusi Nefelejcs",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Nagylevelű Nefelejcs",
      "Latin név": "Brunnera Macrophylla",
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Nagyvirágú Gólyaorr",
      "Latin név": "Geranium Sanguineum",
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Kék Gólyaorr",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Himalájai Gólyaorr",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Viking Feketeberkenye",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Piros Ribizli",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Tüskétlen Szeder",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Pallagi Egres",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Fertődi zamatos Málna",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Fekete Bodza",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Illatos Orgona",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Amerikai Futólonc",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Illatos Futólonc",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Ringlószilva",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Füge",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Madárbirs",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Yucca",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Palmeri Varjúháj",
      "Latin név": "Sedum Palmeri",
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Borsos Varjúháj",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": null,
      "Latin név": "Sedum ternatum",
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": null,
      "Latin név": "Armeria maritima",
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": null,
      "Latin név": "Saxifraga callosa",
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": null,
      "Latin név": "Sempervivum Tectorum",
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": null,
      "Latin név": "Sempervivum Montanum",
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": null,
      "Latin név": "Hebe Andesonii",
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": null,
      "Latin név": "Euphorbia Myrsinites",
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Hasindító Kutyatej",
      "Latin név": "Euphorbia Lathyris",
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": null,
      "Latin név": "Sedum Spurium",
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": null,
      "Latin név": "Sedum Rupestre",
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Dalmát Harangvirág",
      "Latin név": "Campanula Portenschlagiana",
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Pettyes harangvirág",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Csüngő Harangvirág",
      "Latin név": "Campanula Pposcharskyana",
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Baracklevelű Harangvirág",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Közönséges Kökörcsin",
      "Latin név": "Pusatilla Vulgaris",
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Vöröstölgy",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "CsászárTölgy",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Kocsányos Tölgy",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Virágos Kőris",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Oszlopos Gyertyán",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Kínai Galagonya",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Egybibés galagonya",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Mogyoró",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Hósos Som",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Veresgyűrűs som",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Mocsári Hibiscus",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Fekete Mályva",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Mályva cserje",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Japán kövérke",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Méyontófű",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Nagyvirágó Laputurbolza",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Levendula",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Rozmaring",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Kerti Kaukkfű",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Mezei Kakukkfű",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Zsálya",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Majoranna",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Szurokfű",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Citromfű",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Fodormenta",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Borsmenta",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Cickafark",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Lándzsás utifű",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Széleslevelű utifű",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Százszorszép",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Kányazsombor",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Vérehulló Fecskefű",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Fekete nadálytő",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Sárgaárvacsalán",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Vörösárvacsalán",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Havasi ligetszépe",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Díszpipacs",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Vöröshere",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Fehérhere",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Mángold",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Vöröserű Sóska",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Rebarbara",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Erika",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Leander",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Közönséges Borostyán",
      "Latin név": "Hedera helix",
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Tarka Borostyán",
      "Latin név": "Hedera Algeriensis",
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Erdei Szellőrózsa",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Vadgesztenye",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Csörgőfa",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Tulipán variációk",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Fehér Akác",
      "Latin név": null,
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Árlevelű lángvirág",
      "Latin név": "Phlox Subulata",
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    },
    {
      "Magyar név": "Bugás Lángvirág",
      "Latin név": "Phlox Paniculata",
      "Fényigény": null,
      "Tenyészidő": null,
      "Talajigény": null,
      "Habitus": null,
      "Teljes magasság": null,
      "Kiszerelés": null,
      "Virágzás ideje": null,
      "Virág színe": null,
      "Egyéb": null
    }
  ] */

  list: Product[] = [
    {
      _id: '12234dklfsjs',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '3434jlkjlkj43l4',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '434325423542354lkjljlk',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: 'jfdslfkjsdlkjf325432423',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '12234dklfsjs',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '3434jlkjlkj43l4',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '434325423542354lkjljlk',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: 'jfdslfkjsdlkjf325432423',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '12234dklfsjs',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '3434jlkjlkj43l4',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '434325423542354lkjljlk',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: 'jfdslfkjsdlkjf325432423',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '12234dklfsjs',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '3434jlkjlkj43l4',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '434325423542354lkjljlk',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: 'jfdslfkjsdlkjf325432423',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '12234dklfsjs',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '3434jlkjlkj43l4',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '434325423542354lkjljlk',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: 'jfdslfkjsdlkjf325432423',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '12234dklfsjs',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '3434jlkjlkj43l4',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '434325423542354lkjljlk',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: 'jfdslfkjsdlkjf325432423',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '3434jlkjlkj43l4',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '434325423542354lkjljlk',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: 'jfdslfkjsdlkjf325432423',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '3434jlkjlkj43l4',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '434325423542354lkjljlk',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: 'jfdslfkjsdlkjf325432423',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '3434jlkjlkj43l4',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: '434325423542354lkjljlk',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
    {
      _id: 'jfdslfkjsdlkjf325432423',
      name: 'Vasaló',
      description: 'jó vasaló ha vasal a ló',
      price: 22000,
      active: true,
    },
  ];

  apiUrl = environment.apiUrl;

  constructor(
    private http: HttpClient,
  ) { }

  getAll(): Observable<Product[]> {
    // return this.http.get<Product[]>(`${this.apiUrl}product`);
    return of(this.list);
  }

}
